import Head from "next/head";
import Topo from "@/components/Topo";
import Conteudo from "@/components/Conteudo";
import Contatos from "@/components/Contatos";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topo />
      <Conteudo />
    </>
  );
}


